name: Deploy to EC2

on:
  workflow_dispatch:
  pull_request: 
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # 1. Pull the latest code to a temp directory
          rm -rf ~/deploy_temp

          git clone https://github.com/OniSamuelOpeyemi/MarkerPeak_Ecommerce.git ~/deploy_temp
          cd ~/deploy_temp
          git init

          # 2. Remove all contents inside /usr/share/nginx/html but not the folder itself
          sudo rm -rf /usr/share/nginx/html/*

          # 3. Copy new files from the subfolder to sudo rm -rf /usr/share/nginx/html/*
          sudo cp -r ~/deploy_temp/2130_waso_strategy/* sudo rm -rf /usr/share/nginx/html/

          # 4. (Optional) Clean up temp directory
          rm -rf ~/deploy_temp
          sudo systemctl restart nginx